{
  "hash": "f311e76e6e28efa18abb5860c27f6e2a",
  "result": {
    "markdown": "---\ntitle: \"Hello, Penguins\"\nauthor: \"Lukman Aliyu\"\nformat: \n  html: default\n  pdf: default\nexecute: \n  echo: true\neditor: visual\nbibliography: references.bib\n---\n\n\n\n# Introduction\n\nI have been learning data science as a fellow of the Arewa Data Science Academy since January, 2023 and I have picked many skills. This is an attempt to practice quarto using the R programming language, in the RStudio IDE. I will work on the palmerpenguins dataset. Work in progress!!\n\n## Data {.smaller}\n\nFor this analysis, we 'll use the penguins dataset from the palmerpenguins package. [@gorman2014]\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 344\nColumns: 8\n$ species           <fct> Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adel~\n$ island            <fct> Torgersen, Torgersen, Torgersen, Torgersen, Torgerse~\n$ bill_length_mm    <dbl> 39.1, 39.5, 40.3, NA, 36.7, 39.3, 38.9, 39.2, 34.1, ~\n$ bill_depth_mm     <dbl> 18.7, 17.4, 18.0, NA, 19.3, 20.6, 17.8, 19.6, 18.1, ~\n$ flipper_length_mm <int> 181, 186, 195, NA, 193, 190, 181, 195, 193, 190, 186~\n$ body_mass_g       <int> 3750, 3800, 3250, NA, 3450, 3650, 3625, 4675, 3475, ~\n$ sex               <fct> male, female, female, NA, female, male, female, male~\n$ year              <int> 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007~\n```\n:::\n:::\n\n\n\n## Meet Quarto\n\nQuarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.\n\n## Meet the penguins\n\n![](https://raw.githubusercontent.com/quarto-dev/quarto-web/main/docs/get-started/hello/rstudio/lter_penguins.png){style=\"float:right;\" fig-alt=\"Illustration of three species of Palmer Archipelago penguins: Chinstrap, Gentoo, and Adelie. Artwork by @allison_horst.\" width=\"401\"}\n\nThe `penguins` data from the [**palmerpenguins**](https://allisonhorst.github.io/palmerpenguins \"palmerpenguins R package\") package contains size measurements for 344 penguins from three species observed on three islands in the Palmer Archipelago, Antarctica.\n\nThe plot below shows the relationship between flipper and bill lengths of these penguins.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-pdf/plot-penguins-1.pdf)\n:::\n:::\n\n\n\n## Species\n\n@fig-bill-dim-species is a scatter plot of species of penguins\n\n\n\n::: {.cell fig.asp='0.618'}\n\n```{.r .cell-code}\nggplot(penguins,\n       aes(x=bill_length_mm, y= bill_depth_mm,color=species,shape=species)) + geom_point() + theme_minimal() + scale_color_colorblind()  + labs( x = \"Bill length (mm)\", y = \"Bill depth (mm)\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 2 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![A scatterplot of penguin's bill depth and length, colored by species of penguins.\noutput-location: slide](index_files/figure-pdf/fig-bill-dim-species-1.pdf){#fig-bill-dim-species fig-pos='H' fig-alt='A scatterplot of penguin\\'s bill depth and length, colored by species of penguins. There is a relatively strong linear association.\n'}\n:::\n:::\n\n\n\n## Penguins\n\n@tbl-penguins-top10 shows the first ten penguins from the dataset.\n\n\n\n::: {#tbl-penguins-top10 .cell tbl-cap='First 10 penguins.'}\n\n```{.r .cell-code}\npenguins %>%\n  slice_head(n=10) %>%\n  select(species,island,bill_length_mm,bill_depth_mm) %>%\n  gt()\n```\n\n::: {.cell-output-display}\n\\begin{longtable}{ccrr}\n\\toprule\nspecies & island & bill\\_length\\_mm & bill\\_depth\\_mm \\\\ \n\\midrule\nAdelie & Torgersen & 39.1 & 18.7 \\\\ \nAdelie & Torgersen & 39.5 & 17.4 \\\\ \nAdelie & Torgersen & 40.3 & 18.0 \\\\ \nAdelie & Torgersen & NA & NA \\\\ \nAdelie & Torgersen & 36.7 & 19.3 \\\\ \nAdelie & Torgersen & 39.3 & 20.6 \\\\ \nAdelie & Torgersen & 38.9 & 17.8 \\\\ \nAdelie & Torgersen & 39.2 & 19.6 \\\\ \nAdelie & Torgersen & 34.1 & 18.1 \\\\ \nAdelie & Torgersen & 42.0 & 20.2 \\\\ \n\\bottomrule\n\\end{longtable}\n:::\n:::\n\n\n\n# Analysis\n\n## Modelling Results\n\n# References\n",
    "supporting": [
      "index_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "\\usepackage{booktabs}\n\\usepackage{caption}\n\\usepackage{longtable}\n"
      ]
    },
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}